#!/usr/bin/expect

# uncomment line below for debugging
# exp_internal 1

set timeout 7

source ./ci/expect_scripts/shared-code.exp

spawn $env(EXAMPLES_DIR)dir-test

expect "Created test-dir\r\n" {
    expect "Created test-nested/a/b/c\r\n" {
        expect -re "Contents: test-nested/a\r\n" {
            expect "Cleaned up!\r\n" {
                expect eof {
                    check_exit_and_segfault
                }
            }
        }
    }
}

puts stderr "\nExpect script failed: output was different from expected value. uncomment `exp_internal 1` to debug."
exit 1
